//
// Created by ASUS on 10/5/2017.
//

#ifndef LOGOLICIOUS_SVNLIVE_JNIBITMAPOPERATIONSLIBRARY_H
#define LOGOLICIOUS_SVNLIVE_JNIBITMAPOPERATIONSLIBRARY_H


class JniBitmapOperationsLibrary {

};


#endif //LOGOLICIOUS_SVNLIVE_JNIBITMAPOPERATIONSLIBRARY_H
